version = 0.1
[default.deploy.parameters]
stack_name = "backend-restaurante-template-aws-sam"
resolve_s3 = true
s3_prefix = "backend-restaurante-template-aws-sam"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "AppName=\"restaurante\" AppEnv=\"dev\""
image_repositories = []
